financial_analytics: 
  outputs:
    bigquery:
      type: bigquery
      method: service-account
      project: de-final-project-2026
      dataset: raw
      keyfile: /opt/airflow/credentials/service-account.json
      threads: 4
      timeout_seconds: 300
      location: asia-southeast2
  target: bigquery