version: '3.8'

x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: airflow.Dockerfile
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: '${AIRFLOW_FERNET_KEY}'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    AIRFLOW__CORE__LOGGING_LEVEL: INFO
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    # Konfigurasi Path dbt & GCP Service Account
    DBT_PROFILES_DIR: /opt/airflow/dbt
    GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/credentials/service-account.json
    
    # Auto-create akun Admin Airflow
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: 'airflow:admin'
    AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS: 'true'

    # 🔑 KUNCI SAKTI: Menyamakan token keamanan agar tidak 403 Forbidden lagi
    AIRFLOW__API_AUTH__JWT_SECRET: 'rahasia-kita-berdua-biar-ga-error-lagi-123'
    AIRFLOW__API__AUTH_JWT_SECRET: 'rahasia-kita-berdua-biar-ga-error-lagi-123'
    AIRFLOW__WEBSERVER__SECRET_KEY: 'rahasia-kita-berdua-biar-ga-error-lagi-123'
    
  volumes:
    - ./container/dags:/opt/airflow/dags
    - ./container/logs:/opt/airflow/logs
    - ./container/config:/opt/airflow/config
    - ./dbt:/opt/airflow/dbt
    - ./credentials:/opt/airflow/credentials
    - ./ingestion:/opt/airflow/ingestion
  depends_on:
    postgres:
      condition: service_healthy

services:
  # 1. Metadata Database untuk Airflow
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Airflow Webserver / API Server (UI)
  airflow-apiserver:
    <<: *airflow-common
    command: api-server
    ports:
      - "8080:8080"
    restart: always

  # 3. Airflow Scheduler (Mesin Orkestrasi)
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

  # 4. Airflow DAG Processor (Eksekutor DAG)
  airflow-dag-processor:
    <<: *airflow-common
    command: dag-processor
    restart: always

  # 5. Metabase (BI Tool)
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3001:3000"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: airflow
      MB_DB_PASS: airflow
      MB_DB_HOST: postgres
    restart: always
  
volumes:
  postgres_data: